# Support Vector Machine (SVM)


In the Data.analysis notebook Logistic Regression pipielines were computed for classifying the participants either as control or patient.This notebook is a continuation of the Data.analysis notebook and serves the purpose of computing **SVM** pipelines for macro-structural and micro-structural data.

## 1. What are Support Vector Machines (SVMs) ?

SVMs are a set of supervised learning methods used that can be used for classifcation, regression and outliers detection (for further information click here). The basic idea is to find an optimal separating line (or hyperplane) as output that separates the data into two classes. The SVM algorithm looks for the data points that are the clostest to the line from both classes. These points are called support vectors. Then, the distance between the support vectors and the hyperplane which is called the margin is computed. To find the best and optimal hyperplane, the margin should be maximized.


Support vector classification (SVC) or Linear Support vector classification (LinearSVC) are methods of SVMs making it feasible to perfom a binary or mulit-class classification on a dataset. For the purpose of this project, LinearSVC is going to be performed.

## 2. Macro-structural data: Cortical Thickness (CT)

In this section, a SVM pipeline will be computed for the macro-structual data **CT**. Firstly, the data is loaded and prepared for the analysis part. Secondly, the SVM model is built containing the analysis. Finally, we evaluate our model and have a look at how it performs. 

### 2.1 Data preparation 

In [1]:
#import relevant modules

import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics

In [48]:
#load data

CT_Dublin_path = os.path.join(os.pardir, 'data', 'PARC_500.aparc_thickness_Dublin.csv')
CT_Dublin = pd.read_csv(CT_Dublin_path)

In [3]:
#adjust dataframe

CT_Dublin_adj = CT_Dublin.drop(['Subject ID','Age', 'Sex'], axis=1)

In [4]:
#label group 1 as 0 and 2 as 1

CT_Dublin_adj['Group'] = CT_Dublin_adj['Group'].replace([1,2],[0, 1])

In [49]:
#print the names of the 308 features

print("Features: ", CT_Dublin_adj.columns[2:308])

Features:  Index(['lh_bankssts_part2_thickness',
       'lh_caudalanteriorcingulate_part1_thickness',
       'lh_caudalmiddlefrontal_part1_thickness',
       'lh_caudalmiddlefrontal_part2_thickness',
       'lh_caudalmiddlefrontal_part3_thickness',
       'lh_caudalmiddlefrontal_part4_thickness', 'lh_cuneus_part1_thickness',
       'lh_cuneus_part2_thickness', 'lh_entorhinal_part1_thickness',
       'lh_fusiform_part1_thickness',
       ...
       'rh_supramarginal_part4_thickness', 'rh_supramarginal_part5_thickness',
       'rh_supramarginal_part6_thickness', 'rh_supramarginal_part7_thickness',
       'rh_frontalpole_part1_thickness', 'rh_temporalpole_part1_thickness',
       'rh_transversetemporal_part1_thickness', 'rh_insula_part1_thickness',
       'rh_insula_part2_thickness', 'rh_insula_part3_thickness'],
      dtype='object', length=306)


In [51]:
#print the names of the labels

print("Labels: ", CT_Dublin_adj['Group'])

Labels:  0      0
1      0
2      0
3      1
4      1
      ..
103    1
104    1
105    1
106    1
107    1
Name: Group, Length: 108, dtype: int64


### 2.2 Building the model

As in the Data.analysis notebook, as a first step the input and output data should be defined. It is analogous to the Logistic Regression input and output since it is the identical **CT** data.

In [54]:
#define data and target

CT_data = CT_Dublin_adj.iloc[:,1:308].values
CT_target = CT_Dublin_adj.iloc[:,[0]].values

In [52]:
CT_data

array([[2.18 , 2.382, 2.346, ..., 3.62 , 2.776, 3.282],
       [2.394, 1.973, 2.534, ..., 3.588, 2.654, 3.124],
       [2.551, 2.567, 1.954, ..., 3.657, 2.495, 2.669],
       ...,
       [2.273, 2.559, 2.578, ..., 3.48 , 2.294, 2.571],
       [1.94 , 2.438, 2.272, ..., 3.187, 2.51 , 2.759],
       [2.108, 2.269, 2.145, ..., 3.192, 2.551, 2.855]])

In [55]:
CT_target

array([[0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
    

In [9]:
#split data

CT_X_train, CT_X_test, CT_y_train, CT_y_test = train_test_split(CT_data, CT_target, test_size=0.3,random_state=109)

In [10]:
classifier = svm.SVC(kernel='linear')

In [11]:
CT_target

array([[0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
    

In [12]:
CT_target.shape

(108, 1)

In [13]:
CT_target = CT_target.ravel()

In [14]:
CT_target.shape

(108,)

In [15]:
classifier.fit(CT_X_train, CT_y_train)

/Users/mello/miniconda3/envs/neuro_ai/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [16]:
CT_y_pred = classifier.predict(CT_X_test)

In [17]:
print("Accuracy:",metrics.accuracy_score(CT_y_test, CT_y_pred))
print("Precision:",metrics.precision_score(CT_y_test, CT_y_pred))
print("Recall:",metrics.recall_score(CT_y_test, CT_y_pred))

Accuracy: 0.8484848484848485
Precision: 1.0
Recall: 0.5454545454545454


## Micro-structural data

### Mean Diffusivity

In [18]:
#read data

MD_Dublin_path = os.path.join(os.pardir, 'data', 'PARC_500.aparc_MD_cortexAv_mean_Dublin.csv')
MD_Dublin = pd.read_csv(MD_Dublin_path)

In [19]:
#adjust dataframe

MD_Dublin_adj = MD_Dublin.drop(['Subject ID','Age', 'Sex'], axis=1)

In [20]:
#label group 1 as 0 and 2 as 1

MD_Dublin_adj['Group'] = MD_Dublin_adj['Group'].replace([1,2],[0, 1])

In [21]:
MD_Dublin_adj

Group  lh_bankssts_part1_thickness  lh_bankssts_part2_thickness  \
0        0                        0.911                        0.931   
1        0                        0.861                        0.913   
2        0                        0.817                        0.827   
3        0                        0.887                        0.905   
4        0                        0.887                        0.854   
..     ...                          ...                          ...   
110      1                        0.843                        0.855   
111      1                        0.911                        0.914   
112      1                        0.890                        0.899   
113      1                        0.920                        0.986   
114      1                        0.970                        0.868   

     lh_caudalanteriorcingulate_part1_thickness  \
0                                         0.891   
1                                         0.846   
2                                         0.828   
3                                         0.878   
4                                         0.905   
..                                          ...   
110                                       0.940   
111                                       0.926   
112                                       0.886   
113                                       0.883   
114                                       0.940   

     lh_caudalmiddlefrontal_part1_thickness  \
0                                     1.048   
1                                     0.927   
2                                     0.828   
3                                     0.932   
4                                     1.011   
..                                      ...   
110                                   1.017   
111                                   1.001   
112                                   0.930   
113                                   0.879   
114                                   0.967   

     lh_caudalmiddlefrontal_part2_thickness  \
0                                     0.881   
1                                     0.888   
2                                     0.780   
3                                     0.820   
4                                     0.946   
..                                      ...   
110                                   0.954   
111                                   0.918   
112                                   0.883   
113                                   0.794   
114                                   0.930   

     lh_caudalmiddlefrontal_part3_thickness  \
0                                     0.939   
1                                     0.894   
2                                     0.843   
3                                     0.888   
4                                     0.922   
..                                      ...   
110                                   0.840   
111                                   1.115   
112                                   0.882   
113                                   0.983   
114                                   1.022   

     lh_caudalmiddlefrontal_part4_thickness  lh_cuneus_part1_thickness  \
0                                     1.124                      0.986   
1                                     0.924                      1.040   
2                                     0.825                      0.848   
3                                     0.970                      0.918   
4                                     1.034                      1.126   
..                                      ...                        ...   
110                                   1.128                      1.012   
111                                   1.036                      1.026   
112                                   0.883                      1.190   
113                                   1.029                      1.076   
114               

In [22]:
#define input and output

MD_data = MD_Dublin_adj.iloc[:,1:308].values
MD_target = MD_Dublin_adj.iloc[:,[0]].values

In [23]:
MD_X_train, MD_X_test, MD_y_train, MD_y_test = train_test_split(MD_data, MD_target, test_size=0.3,random_state=109)

In [24]:
MD_classifier = svm.SVC(kernel='linear')

In [25]:
MD_classifier.fit(MD_X_train, MD_y_train)

/Users/mello/miniconda3/envs/neuro_ai/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [26]:
MD_y_pred = MD_classifier.predict(MD_X_test)

In [27]:
print("Accuracy:",metrics.accuracy_score(MD_y_test, MD_y_pred))
print("Precision:",metrics.precision_score(MD_y_test, MD_y_pred))
print("Recall:",metrics.recall_score(MD_y_test, MD_y_pred))

Accuracy: 0.8571428571428571
Precision: 1.0
Recall: 0.5


## Fractional Anisotropy

In [28]:
#read data

FA_Dublin_path = os.path.join(os.pardir, 'data', 'PARC_500.aparc_FA_cortexAv_mean_Dublin.csv')
FA_Dublin = pd.read_csv(FA_Dublin_path)

In [29]:
#adjust dataframe

FA_Dublin_adj = FA_Dublin.drop(['Subject ID','Age', 'Sex'], axis=1)

In [30]:
#label group 1 as 0 and 2 as 1

FA_Dublin_adj['Group'] = FA_Dublin_adj['Group'].replace([1,2],[0, 1])

In [31]:
#define input and output

FA_data = FA_Dublin_adj.iloc[:,1:308].values
FA_target = FA_Dublin_adj.iloc[:,[0]].values

In [32]:
#split data

FA_X_train, FA_X_test, FA_y_train, FA_y_test = train_test_split(FA_data, FA_target, test_size = 0.25, random_state = 0)

In [33]:
FA_classifier = svm.SVC(kernel='linear')

In [34]:
FA_classifier.fit(FA_X_train, FA_y_train)

/Users/mello/miniconda3/envs/neuro_ai/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [35]:
FA_y_pred = FA_classifier.predict(FA_X_test)

In [36]:
print("Accuracy:",metrics.accuracy_score(FA_y_test, FA_y_pred))
print("Precision:",metrics.precision_score(FA_y_test, FA_y_pred))
print("Recall:",metrics.recall_score(FA_y_test, FA_y_pred))

Accuracy: 0.6896551724137931
Precision: 0.0
Recall: 0.0


/Users/mello/miniconda3/envs/neuro_ai/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
